### ISSUE TITLE
Tab overflow a11y design solution

### ISSUE THREAD

**Issue by colinreedmiller** [clr-team/planning#79]
Research and analysis with dev and a11y have arrived at a solution for this:

The tab component needs the following changes to meet a11y compliance:
1. Remove ARIA
2. Remove arrow key navigation
3. Add skiplink as 1st focusable item in tab container.
skiplink design:  https://github.com/vmware/clarity/issues/3153

@Jinnie

**Comment by Jinnie** [comment]
@colinreedmiller I need more information on the proposed solution.

The points that are confusing me:
- Remove ARIA - need more info, what does that mean?
- Remove arrow key navigation - substitute it with what?
- How the above two requests make the component more accessible, or accessible at all? These requirements contradict with the W3C requirements for tabs and menus.
- Add skip link - I, as a developer, can't even imagine what would I use a skip link for in the tabs component. Please provide more information.
- On what is your parallel research based? My current solution is based on
    - the W3C recommendations for tabs and menus:
       - https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html
       - https://www.w3.org/WAI/GL/wiki/Using_ARIA_menus
    - on numerous iterations of prototypes and demos, presented to the team and to @chlane personally.
    - on a month-long open PR reviewed by the team and discussed on open slack channels and interested colleagues.
- If dev and a11y have participated in the here referenced research and analysis, that makes me ask:
    - why I have not been involved on the dev part, as I am the dev owner of about 5 a11y task specifically targeted at this and having spent more than a month dev time on a highly complex task, which is currently in a ready-to-merge state:
https://github.com/vmware/clarity/pull/3609
    - why there is so much difference between my talks with a11y representatives and the here proposed approach

**Comment by clane** [comment]
**Remove ARIA - need more info, what does that mean?**
It means as step 1 is to remove all ARIA from the Clarity Tabs overflow component. The goes back to the original problem, that we are not following the ARIA spec for a tabs implementation when we introduce an overflow button/link into the middle of an element with role="tablist" which should only contain elements with role="tab".

Not using ARIA at all is better than implementing incorrectly. 

So remove role="tablist", role="tab" and role="tabpanel".

Remove arrow key navigation - substitute it with what?

The non-ARIA tabs can be implemented with buttons or links. These will key be keyboard accessible and focusable with the Tab key.

**Add skip link - I, as a developer, can't even imagine what would I use a skip link for in the tabs component. Please provide more information.**

You would add a skip link so that sighted keyboard-only users can skip over the non-ARIA tabs with the TAB key. The skip link should be placed before the non-ARIA tabs and the skip links target would immediately follow it.

**On what is your parallel research based?**
Sighted keyboard only users and testers will notice that they can't focus the '...' tab. Ivan has done a great job making this work under the hood but there appears to be no visual design option that fixes the issue that the '...' is visually present and that sighted keyboard-only users/testers will notice this immediately.

**If dev and a11y have participated in the here referenced research and analysis, that makes me ask:
why I have not been involved on the dev part, as I am the dev owner of about 5 a11y task specifically targeted at this and having spent more than a month dev time on a highly complex task, which is currently in a ready-to-merge state:
vmware/clarity#3609**

I was told there would be a visual design treatment that made this solution work. When we (Jeeyun, Colin and I) met we were to discuss a design that works with your implementation and found that there is none. I have been opposed to this implementation from the start but was told that it would be fixed on the design side. When we realized this is not possible, I recommended to abandon the ARIA tabs implementation.

**why there is so much difference between my talks with a11y representatives and the here proposed approach.**

The is the a11y recommendation **now** that I have been informed that a design cannot be created that prevents sighted keyboard-only users/testers from thinking that they can interact with the '...' control using the arrow keys as they would with the adjacent tabs.

**Comment by clane** [comment]
Just spoke to Sheri and she said she agrees that our current design and implementation could be flagged by an a11y tester for the inability of sighted-keyboard only users to directly activate the '...' control. She also agrees that removing the ARIA and going with links/buttons is the best solution.

But since we have already implemented ARIA tabs with this one problem, she recommends keeping this implementation and living with this issue even though it could be flagged by external testers.
